### ISSUE TITLE
Add `## Session Info` at the end of each chapter

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/OrchestratingSingleCellAnalysis#2]
(suggestion)
At least for the chapters that do contain references.
Otherwise, the references appear a bit out of nowhere, straight after the sessionInfo.

**Comment by federicomarini** [comment]
IMHO even better, we could have it as unnumbered section with
`# Session info {-}`

**Comment by kevinrue** [comment]
See e1f154decf63a82de1c7bd7c190723e08cd49cb4 for example
