### ISSUE TITLE
Figure 5.1 broken link

### ISSUE THREAD

**Issue by johnomics** [Bioconductor/OrchestratingSingleCellAnalysis#20]
Hello,

Thank you for writing such an excellent guide to single cell analysis.

Figure 5.1 is currently missing:
https://osca.bioconductor.org/overview.html

The image is still in the repository:
https://github.com/Bioconductor/OrchestratingSingleCellAnalysis/blob/master/images/Workflow.png

But the link appears to be incorrect, at line 46 of [P2_W01.overview.md](https://github.com/Bioconductor/OrchestratingSingleCellAnalysis/blob/b1e02da8ac07b770453c4863ef32d85e0a84bec9/docs/P2_W01.overview.md), which is then being propagated to line 676 of overview.html:
https://github.com/Bioconductor/OrchestratingSingleCellAnalysis/blob/ed0b0930ab65a157fd5af8e8d4915adfb885cf70/docs/overview.html#L676

Please could you look into this? Thanks!

**Comment by LTLA** [comment]
Interesting. It seems like compiling a chapter with **rmarkdown** will embed an image into the HTML, but compiling with **bookdown** presumably just links to an image. Thanks for spotting this, given that the yet-to-be-compiled latest version of the book will encounter this problem for all of the external images. (Alas, my memes!)

**Comment by johnomics** [comment]
No problem - just noticed another even smaller bug too small for its own issue - Chapter 6 currently has two links to Section ??, because there is no quality-control-discarded anchor in [P2_W02.quality-control.md](https://github.com/Bioconductor/OrchestratingSingleCellAnalysis/blob/b1e02da8ac07b770453c4863ef32d85e0a84bec9/docs/P2_W02.quality-control.md).

**Comment by LTLA** [comment]
Oh, yeah, broken links are all over the place in that thing. I could get to them eventually, but you seem to be reading through the book anyway, so if you could list them (or even better, make a PR and fix them), that would be nice.

**Comment by johnomics** [comment]
Sure, I'll at least report them where I see them and fix them if I can. Thanks again for the great book.
