### ISSUE TITLE
package ‘OSCAUtils’ is not available (for R version 3.6.2)”

### ISSUE THREAD

**Issue by parsboy66** [Bioconductor/OrchestratingSingleCellAnalysis#25]
hello
I'm working by R v.3.6
but it seems library (OSCAUtils) is not supported by this version of R. when ever I tried to install this package, I faced with the error package ‘OSCAUtils’ is not available (for R version 3.6.2)”

**Comment by kevinrue** [comment]
Hi
The `OSCAUtils` package is distributed as a subfolder of this repository, see:
https://github.com/Bioconductor/OSCABase/tree/master/package

See the `DESCRIPTION` file in that folder that declares the package name: https://github.com/Bioconductor/OSCABase/blob/master/package/DESCRIPTION#L1

To install `OSCAUtils`, any of the following should work:
```r
BiocManager::install("Bioconductor/OSCABase", subdir = "package")
devtools::install_github("Bioconductor/OSCABase", subdir = "package")
```

**Comment by parsboy66** [comment]
Problem solved, but keep in mind this library needs 2 other packages which are not frequently used and users should install it in advance. 
as I am working on Conda env. I leave the instruction below to install those libs. for anybody who faced the same problem. 


conda install -c conda-forge/label/cf201901 r-tinytex
conda install -c biobuilds r-stringi

also its better to use force= TRUE in this one.
BiocManager::install("Bioconductor/OSCABase", subdir = "package" ,force=TRUE)

Appreciate it and thank you for replying appropriately.

**Comment by LTLA** [comment]
I'm kind of bemused about why you need to install **OSCAUtils**. This is a package that is literally only required to build the book, not to run any of the analysis code in the book.

I mean, if you want to use it, that's cool and all, but don't expect it to be stable.
