### ISSUE TITLE
Operationalize RNA velocity section

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/OrchestratingSingleCellAnalysis#29]
- @csoneson to make an unspliced dataset available in **scRNAseq**.
- other volunteers to create a dedicated R wrapper around `scvelo` or `velocyto`, or both.

**Comment by csoneson** [comment]
I just sent a PR for `scRNAseq` with spliced and unspliced counts from a part of [Hermann et al (2018)](https://pubmed.ncbi.nlm.nih.gov/30404016/).

**Comment by csoneson** [comment]
I was also toying with an R wrapper package for `scVelo` based on `basilisk`: https://github.com/csoneson/scvelor. Still very early-stage though. Perhaps @lazappi would be interested in joining the effort?

**Comment by csoneson** [comment]
> I was also toying with an R wrapper package for `scVelo` based on `basilisk`: https://github.com/csoneson/scvelor. Still very early-stage though. Perhaps @lazappi would be interested in joining the effort?

Well, I guess this was a bit redundant, I just noticed that you already started this with `velociraptor`

**Comment by LTLA** [comment]
Excellent. A few points:

- It would be good to have a very lightweight package whose only job is to convert SCEs to/from AnnData objects. This code could then be re-used in downstream packages like **velociraptor**. Some care is required to ensure that our Python dependencies are kept in sync, but I'm sure it can be done, e.g., provide a function to report the **AnnData** versions for use by downstream packages.
- Yes, please put further development effort into **velociraptor**. The main missing piece is a similar wrapper for the original **velocyto**, which is why we gave it a more general name than **scvelor**. Who knows, there will probably be more velocity methods in the future. Another contribution would be to expose more API points, e.g., can we plug in our own reduced dimensions or nearest neighbors? Ideally as much work would be done in R as possible, for consistency with the rest of our analysis pipelines, and we would only enter Python for the final velocity calculations.

**Comment by csoneson** [comment]
I think the arguments of the `scVelo` functions need to be exposed as well. I thought about providing a list of lists (with one element per `scVelo` function, being a list where any argument to the corresponding function can be set if you want a non-default value). E.g. https://github.com/csoneson/scvelor/blob/3f5102508f727e93cbc465be0928d643e60cf7af/R/scvelor.R#L64-L66

**Comment by LTLA** [comment]
One could indeed do that. I don't particularly care much until it gets to the `velocity` function, everything else we can do inside R with **BiocNeighbors** and **BiocSingular**.

**Comment by lazappi** [comment]
I would be interested in helping out with this if there is anything you need a hand with, it's something I have thought about but never got around to. Also happy to liaise with the **scVelo**/**AnnData** authors if needed (given I am in the same lab).

**Comment by LTLA** [comment]
Should you care to build an **AnnData** converter, I'm sure **velociraptor** would use it.

**Comment by lazappi** [comment]
I have started a conversion package here https://github.com/theislab/zellkonverter. It just has basic functions for reading `.h5ad` files and converting `AnnData` to `SingleCellExperiment` so far.

Comments/suggestions/contributions welcome!
