### ISSUE TITLE
Interpretation Figure 7.7 in Chapter 7.4.2 Differential Expression

### ISSUE THREAD

**Issue by tmms1** [Bioconductor/OrchestratingSingleCellAnalysis#3]
You show a violin plot in Chapter 7.4.2 (Figure 7.7) of the excellent workflow “Orchestrating Single-Cell Analysis with Bioconductor”. However, I am confused about the text accompanying the figure:
“This plot highlights that CD3D is more highly expressed in cluster 1 relative to some of the other clusters, but not all. This can also be seen from our raw output above, where the log fold-change is calculated with respect to each cluster. There, we see that the log fold-change for CD3D is very high only relative to clusters 2 and 3 (meeting our cutoff of 1.5).”
 
How do you see that CD3D is more highly expressed in cluster 1 relative to some other clusters? Based on the plot, I thought that CD3D is more highly expressed in cluster 3,4,5 compared to clusters 1 and 2 (because the mean expression of clusters 3,4,5 is higher than in cluster 1 and 2). 
Moreover, CD3D is not present in the raw output above the figure.

Thanks in advance.

**Comment by LTLA** [comment]
You can chalk this one up to us not keeping the text up to date with the code. Probably something changed slightly upstream and the cluster labels got swapped around, no big deal. This is a perennial problem for anyone who writes workflows - it'll get fixed at some point.

**Comment by LTLA** [comment]
This should no longer be a problem... by the simple expedient of removing the entire section.
