### ISSUE TITLE
Include count-based dimensionality reduction options

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/OrchestratingSingleCellAnalysis#30]
These would be appealing to avoid the mean-variance issues with the log-transformation prior to PCA.

Considering **scry** pending some improvements to efficiency (kstreet13/scry#7). I'd like to see that example get down to a minute's runtime so that the book chapter runs fairly quickly. Tagging @willtownes to keep track of this.

**Comment by LTLA** [comment]
May also put in the correspondence analysis from **corral**, tagging @laurenhsu1.

**Comment by laurenhsu1** [comment]
That would be great! Is there already a section written about this, or should I draft/PR something?

**Comment by LTLA** [comment]
The relevant chapter would be `reduced-dimensions.Rmd`, but I was planning to just write that part myself. My understanding is that I can give **corral** a count matrix and it will give me a reduced dimensions; if that is correct, then the process should be simple enough. I do have some questions that I'll send to laurenhsu1/corral#2, though.
