### ISSUE TITLE
code can't run successfully in 5th and 6th chapter

### ISSUE THREAD

**Issue by yjm1992312** [Bioconductor/OrchestratingSingleCellAnalysis#32]
When I read the 5th chapter about Overview, I run the code

library(scRNAseq)

sce <- MacoskoRetinaData() and then excute in Rstudio, it errors and indicates no MacoskoRetinaData function.
 

And the same problem exists in chapter 6, when I run

library(scRNAseq)

sce.416b<-LunSpikeInData(which="416b")

sce.416b$block<-factor(sce.416b$block)

it also errors with no LunSpikeInData function. Then I refer to the documentation of package scRNAseq, there is the same code in the documentation. So I’m confused and wonder why I can’t run the code successfully.

**Comment by PeteHaitch** [comment]
What is the output of `BiocManager::valid()` on your system?
By and large, you will need to be running the same version of packages to reproduce the results of the book.

**Comment by LTLA** [comment]
What he said.

**Comment by yjm1992312** [comment]
> 
> 
> What is the output of `BiocManager::valid()` on your system?
> By and large, you will need to be running the same version of packages to reproduce the results of the book.

**Comment by yjm1992312** [comment]
Thank you very much, I have solve the problem by updating the R version from R(3.6.3) to R (4.0.1),and update the package scRNAseq from version 1.16.0 to 2.2.0.
