### ISSUE TITLE
Guideline to contribute?

### ISSUE THREAD

**Issue by mdmanurung** [Bioconductor/OrchestratingSingleCellAnalysis#50]
Dear all,

Is there any guideline to contribute to this awesome book?

For example, I would like to contribute to Chapter 8, which is on Feature Selection, by writing something about feature selection by deviance using `glmpca`. Should I just make a pull request or should I communicate my intent with someone beforehand?

Best regards,
Mikhael

**Comment by kevinrue** [comment]
Hi @MikhaelManurung 

Most of the information to contribute in the main README of this repository: https://github.com/Bioconductor/OrchestratingSingleCellAnalysis#developer-instructions

I'd say the clearest way to communicate your intention is to prepare your contribution and send in a PR that people will then be able to review and comment on (in the PR thread), which will may lead through some iterations to iron out any specific fixes and clarifications.

Best
Kevin

**Comment by LTLA** [comment]
For `glmpca()`, it would be helpful to coordinate with the **scry** maintainers so that the code in the book becomes as simple as:

```r
dev.res <- scry::selectByDeviance(sce)
```

For example. Would also be nice if I could then do `hvgs <- scran::getTopHVGs(dev.res, var.field="whatever", n=2000)`.

**Comment by mdmanurung** [comment]
Hi @kevinrue and @LTLA,

Thanks for the information. I look forward to making some contributions.

Best regards,
Mikhael
