### ISSUE TITLE
can not download LunSpikeInData

### ISSUE THREAD

**Issue by YinCY123** [Bioconductor/OrchestratingSingleCellAnalysis#57]
the error returns

Error in value[[3L]](cond) : failed to connect
  reason: Timeout was reached: [bioconductor.org] Operation timed out after 10002 milliseconds with 0 out of 0 bytes received
  Consider rerunning with 'localHub=TRUE'

does anybody know how to deal with?

**Comment by LTLA** [comment]
Depends on where you are. ExperimentHub uses AWS S3 to host its data, and, e.g., China has serious connectivity problems with AWS. Sometimes things work, sometimes they don't. In this case, if the error message is to be taken at face value, then it's actually a problem with the bioconductor.org interface rather than S3 itself. Perhaps @lshep can provide some more clarification.

**Comment by lshep** [comment]
I was running some computationally heavy scripts over the weekend trying to analyze some logs. perhaps it interfered.  @YinCY123  can you try again and let us know if you are still having issues?

**Comment by YinCY123** [comment]
> I was running some computationally heavy scripts over the weekend trying to analyze some logs. perhaps it interfered. @YinCY123 can you try again and let us know if you are still having issues?

**Comment by YinCY123** [comment]
yes, I'm located in china, It seems that it still doesn't work. 

I'm using the AnnotationHub()[['AH73905']] to retrieve, it doesn't work either

The verbose return as follows:

snapshotDate(): 2020-04-27
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
snapshotDate(): 2020-04-27
loading from cache
Error: failed to load resource
  name: AH73905
  title: Ensembl 97 EnsDb for Mus musculus
  reason: database disk image is malformed
In addition: Warning messages:
1: call dbDisconnect() when finished working with a connection 
2: Couldn't set synchronous mode: database disk image is malformed
Use `synchronous` = NULL to turn off this warning.

**Comment by lshep** [comment]
This is odd as I cannot reproduce ... 

```
> ah = AnnotationHub()
snapshotDate(): 2021-03-15
ah[["AH7> ah[["AH73905"]]
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%

loading from cache
require("ensembldb")
EnsDb for Ensembl:
|Backend: SQLite
|Db type: EnsDb
|Type of Gene ID: Ensembl Gene ID
|Supporting package: ensembldb
|Db created by: ensembldb package from Bioconductor
|script_version: 0.3.4
|Creation time: Sun Jul  7 08:07:59 2019
|ensembl_version: 97
|ensembl_host: localhost
|Organism: Mus musculus
|taxonomy_id: 10090
|genome_build: GRCm38
|DBSCHEMAVERSION: 2.1
| No. of genes: 56393.
| No. of transcripts: 144404.
|Protein data available.
```

Since it is saying the database is malformed, I'm wondering if it only partially downloaded the main sqlite database. can you try force redownloading the hub.  And as long as that was successful then try again? 
```
ah = refreshHub(hubClass="AnnotationHub")
```

**Comment by YinCY123** [comment]
after refreshHub(hubClass = 'AnnotationHub') ah[['AH73905']] can be download sucessfully, but the LunSpikeData still can not be downloaded  


> sce.416b <- LunSpikeInData(which = "416b")
snapshotDate(): 2020-04-27
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
Error: failed to load resource
  name: EH2674
  title: Lun 416B plus spike-in counts
  reason: error reading from connection

**Comment by lshep** [comment]
Can you also try redownloading ExperimentHub since that is where the LunSpikeData is 
```
refreshHub(hubClass = 'ExperimentHub')
````
I can download that data without issue as well 
``` 
> temp = eh[["EH2674"]]
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%

loading from cache
>
```

**Comment by YinCY123** [comment]
it looks like is the problem connection to be  AWS S3 as @LTLA

**Comment by lshep** [comment]
perhaps this is the intermittent connectivity to China @LTLA  was referring earlier?

**Comment by YinCY123** [comment]
yes, it seems like that

**Comment by YinCY123** [comment]
thanks for your help! @lshep
