### ISSUE TITLE
Tagged release OSCA docker images

### ISSUE THREAD

**Issue by matthewcarlucci** [Bioconductor/OrchestratingSingleCellAnalysis#58]
The bioconductor_docker container maintains tagged releases in parallel to the package releases. Is it possible to start pushing inherited tagged builds for [bioconductor/orchestratingsinglecellanalysis](https://hub.docker.com/r/bioconductor/orchestratingsinglecellanalysis) to allow future reproducibility of the book and any derived works? I believe this should be as simple as:

1. On RELEASE_3_12, increment the bioconductor_docker tag to RELEASE_3_12. 
2. Build as `bioconductor/orchestratingsinglecellanalysis:RELEASE_3_12`. 
3. Push this tagged build to DockerHub.

It seems this is the intended release practice for Bioconductor images based on https://github.com/Bioconductor/bioconductor_docker/blob/master/best_practices.md.

A build of the Dockerfile modification above appears to work. Please let me know if there is anything further I could do to help (PR to relevant branches?).

**Comment by LTLA** [comment]
We could do that, but speaking of the future, we have migrated to a new architecture at https://github.com/OSCA-source/OSCA. So there would need to be a bit of thought as to where the Dockerfile will live and how it would manage the install.

**Comment by LTLA** [comment]
It is done. 

```sh
docker pull bioconductor/orchestratingsinglecellanalysis:RELEASE_3_12
```

Note that `latest` is now somewhat different if you were previously relying on the location of the Rmarkdown files. The R packages should be still the same (more-or-less) so if you just needed the environment, you shouldn't have to worry.

**Comment by matthewcarlucci** [comment]
This appears to be working perfectly for my use case of reproducibly executing code derived from (*i.e.* code not present in the image itself) the version 3.12 book content, thank you!
